name: fluid_splash
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
    - family: MarcellusSC
      fonts:
        - asset: assets/fonts/MarcellusSC-Regular.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf

